name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use PNPM
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.4

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Deploy (Clean)
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: $HOME/clean-locale.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy (Copy)
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: locale
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy (Execute)
      uses: garygrossgarten/github-action-ssh@release
      with:
        command:  $HOME/update-locale.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
